services:
  messenger:
    build:
      context: .
      dockerfile: messenger/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - messenger/.env
    volumes:
      - messenger-db-data:/code/messenger/app/db/data

volumes:
  messenger-db-data:
    driver: local
