[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["timfdev"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
crewai = "^0.95.0"
undetected-chromedriver = "^3.5.5"
pydantic = "^2.10.4"
pydantic-settings = "^2.7.0"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
langchain = "^0.3.14"
langchain-openai = "^0.3.0"
langchain-community = "^0.3.14"
googlemaps = "^4.10.0"
numpy = "^1.22.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
